modLoader = "javafml"
loaderVersion="[${fml},)"
license = "Apache License 2.0"
issueTrackerURL = "https://www.github.com/MelanX/MoreVanillaTools/issues/"

[[mods]]
modId = "morevanillatools"
version="${version}"
displayName = "MoreVanillaTools"
updateJSONURL = "https://assets.melanx.de/updates/morevanillatools.json"
authors = "MelanX"
description = '''
A mod which adds more tools in the vanilla way.
'''

[[dependencies.morevanillatools]]
    modId="forge"
    mandatory=true
    versionRange="[${forge},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.morevanillatools]]
    modId="minecraft"
    mandatory=true
    versionRange="[${minecraft},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.morevanillatools]]
    modId="libx"
    mandatory=true
    versionRange="[1.20.1-5.0.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.morevanillatools]]
    modId="morevanillalib"
    mandatory=false
    versionRange="[1.20.1-5.0.1,)"
    ordering="NONE"
    side="BOTH"
