modLoader = "javafml"
loaderVersion = "[42,)"
license = "Apache License 2.0"
issueTrackerURL = "https://www.github.com/MelanX/MoreVanillaTools/issues/"

[[mods]]
modId = "morevanillatools"
version = "${file.jarVersion}"
displayName = "MoreVanillaTools"
updateJSONURL = "https://assets.melanx.de/updates/morevanillatools.json"
authors = "MelanX"
description = '''
A mod which adds more tools in the vanilla way.
'''

[[dependencies.morevanillatools]]
    modId="forge"
    mandatory=true
    versionRange="[42.0.8,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.morevanillatools]]
    modId="libx"
    mandatory=true
    versionRange="[1.19.1-4.1.1,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.morevanillatools]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.1, 1.20)"
    ordering="NONE"
    side="BOTH"

[[dependencies.morevanillatools]]
    modId="morevanillalib"
    mandatory=false
    versionRange="[1.19.1-4.1.1,)"
    ordering="NONE"
    side="BOTH"
