modLoader="javafml"
loaderVersion="[33,)"
license="MIT License"

[[mods]]
modId="morevanillatools"
version="${file.jarVersion}"
displayName="MoreVanillaTools"
updateJSONURL="https://raw.githubusercontent.com/MelanX/mod-updatechecker-files/master/morevanillatools.json"
authors="MelanX"
description='''
A mod which adds more tools in the vanilla way.
'''

[[dependencies.morevanillatools]]
    modId="forge"
    mandatory=true
    versionRange="[33,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.morevanillatools]]
    modId="morevanillalib"
    mandatory=true
    versionRange="[1.2.9,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.morevanillatools]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.2,)"
    ordering="NONE"
    side="BOTH"
