modLoader = "javafml"
loaderVersion = "[40,)"
license = "Apache License 2.0"
issueTrackerURL = "https://www.github.com/MelanX/MoreVanillaTools/issues/"

[[mods]]
modId = "morevanillatools"
version = "${file.jarVersion}"
displayName = "MoreVanillaTools"
updateJSONURL = "https://assets.melanx.de/updates/morevanillatools.json"
authors = "MelanX"
description = '''
A mod which adds more tools in the vanilla way.
'''

[[dependencies.morevanillatools]]
    modId="forge"
    mandatory=true
    versionRange="[40.0.2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.morevanillatools]]
    modId="morevanillalib"
    mandatory=true
    versionRange="[1.18.2-3.1.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.morevanillatools]]
    modId="libx"
    mandatory=true
    versionRange="[1.18.2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.morevanillatools]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2, 1.19)"
    ordering="NONE"
    side="BOTH"
