modLoader="javafml"
loaderVersion="[4,)"
license="${mod.license}"
issueTrackerURL="${mod.issue_url}"

[[mods]]
modId="${mod.modid}"
version="${mod.version}"
displayName="${mod.name}"
displayURL="${mod.source_url}"
updateJSONURL="https://assets.melanx.de/updates/morevanillatools.json"
authors="MelanX"
description='''
A mod which adds more tools in the vanilla way.
'''

[[dependencies.${mod.modid}]]
    modId="neoforge"
    mandatory=true
    versionRange="[${mod.neoforge},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod.modid}]]
    modId="minecraft"
    mandatory=true
    versionRange="[${mod.minecraft},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod.modid}]]
    modId="libx"
    mandatory=true
    versionRange="[1.21.1-6.0.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod.modid}]]
    modId="morevanillalib"
    mandatory=false
    versionRange="[21.1.2,)"
    ordering="AFTER"
    side="BOTH"
